export default (app) => {
  app.post(
    `/tenant/:tenantId/task`,
    require('./taskCreate').default,
  );
  app.put(
    `/tenant/:tenantId/task/:id`,
    require('./taskUpdate').default,
  );
  app.delete(
    `/tenant/:tenantId/task`,
    require('./taskDestroy').default,
  );
  // CRM approval queue + decisions (registered BEFORE /task/:id so it isn't shadowed).
  app.get(
    `/tenant/:tenantId/task/approvals`,
    require('./taskApprovalsList').default,
  );
  app.post(
    `/tenant/:tenantId/task/:id/approve`,
    require('./taskDecide').taskApprove,
  );
  app.post(
    `/tenant/:tenantId/task/:id/reject`,
    require('./taskDecide').taskReject,
  );
  app.get(
    `/tenant/:tenantId/task`,
    require('./taskList').default,
  );
  app.get(
    `/tenant/:tenantId/task/:id`,
    require('./taskFind').default,
  );
};
