export default (app) => {
  app.post(
    `/tenant/:tenantId/business-info`,
    require('./businessInfoCreate').default,
  );
  app.put(
    `/tenant/:tenantId/business-info/:id`,
    require('./businessInfoUpdate').default,
  );
  // Accept PATCH as alternative to PUT for partial updates
  app.patch(
    `/tenant/:tenantId/business-info/:id`,
    require('./businessInfoUpdate').default,
  );
  app.delete(
    `/tenant/:tenantId/business-info`,
    require('./businessInfoDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/business-info/export`,
    require('./businessInfoExport').default,
  );
  app.get(
    `/tenant/:tenantId/business-info/:id`,
    require('./businessInfoFind').default,
  );
  app.get(
    `/tenant/:tenantId/business-info/autocomplete`,
    require('./businessInfoAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/business-info`,
    require('./businessInfoList').default,
  );
  app.get(
    `/tenant/:tenantId/business-info/:id`,
    require('./businessInfoFind').default,
  );
  app.get(
    `/tenant/:tenantId/business-info/export`,
    require('./businessInfoExport').default,
  );
  app.post(
    `/tenant/:tenantId/business-info/import-file`,
    require('./businessInfoFileImport').default,
  );
  // Backwards-compatible route: accept '/import' as alternative to '/import-file'
  app.post(
    `/tenant/:tenantId/business-info/import`,
    require('./businessInfoFileImport').default,
  );
};
