export default (app) => {
  app.post(
    `/tenant/:tenantId/business-info`,
    require('./businessInfoCreate').default,
  );
  app.put(
    `/tenant/:tenantId/business-info/:id`,
    require('./businessInfoUpdate').default,
  );
  app.get(
    `/tenant/:tenantId/business-info/export`,
    require('./businessInfoExport').default,
  );
  app.get(
    `/tenant/:tenantId/business-info/:id`,
    require('./businessInfoFind').default,
  );
  app.get(
    `/tenant/:tenantId/business-info/autocomplete`,
    require('./businessInfoAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/business-info`,
    require('./businessInfoList').default,
  );
  app.get(
    `/tenant/:tenantId/business-info/:id`,
    require('./businessInfoFind').default,
  );
  app.get(
    `/tenant/:tenantId/business-info/export`,
    require('./businessInfoExport').default,
  );
  app.post(
    `/tenant/:tenantId/business-info/import-file`,
    require('./businessInfoFileImport').default,
  );
};
