import { Router, Request, Response } from 'express';
import PDFDocument from 'pdfkit';

export default function debugRoutes(routes: Router) {
  routes.get('/debug/pdf-test', async (req: Request, res: Response) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 40 });
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', 'attachment; filename="debug-test.pdf"');
      doc.pipe(res);

      doc.fontSize(20).text('PDF Test', { align: 'center' });
      doc.moveDown();
      doc.fontSize(12).text('This is a simple PDF generated by /api/debug/pdf-test for testing purposes.');
      doc.moveDown();
      doc.text(`Generated at: ${new Date().toLocaleString()}`);

      doc.end();
    } catch (err) {
      console.error('debug/pdf-test error', err);
      res.status(500).json({ message: 'Internal error generating PDF' });
    }
  });
}
