export default (app) => {
  app.post(
    `/tenant/:tenantId/memos`,
    require('./memosCreate').default,
  );
  app.put(
    `/tenant/:tenantId/memos/:id`,
    require('./memosUpdate').default,
  );
  app.delete(
    `/tenant/:tenantId/memos`,
    require('./memosDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/memos`,
    require('./memosList').default,
  );
  app.get(
    `/tenant/:tenantId/memos/export`,
    require('./memosExport').default,
  );
  app.get(
    `/tenant/:tenantId/memos/:id`,
    require('./memosFind').default,
  );
};
