export default (app) => {
  app.post(
    `/tenant/:tenantId/patrol`,
    require('./patrolCreate').default,
  );
  app.put(
    `/tenant/:tenantId/patrol/:id`,
    require('./patrolUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/patrol/import`,
    require('./patrolImport').default,
  );
  app.delete(
    `/tenant/:tenantId/patrol`,
    require('./patrolDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/patrol/autocomplete`,
    require('./patrolAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/patrol`,
    require('./patrolList').default,
  );
  app.get(
    `/tenant/:tenantId/patrol/:id`,
    require('./patrolFind').default,
  );
};
