export default (app) => {
  app.post(
    `/tenant/:tenantId/security-guard`,
    require('./securityGuardCreate').default,
  );
  app.put(
    `/tenant/:tenantId/security-guard/:id`,
    require('./securityGuardUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/security-guard/import`,
    require('./securityGuardImport').default,
  );
  app.delete(
    `/tenant/:tenantId/security-guard`,
    require('./securityGuardDestroy').default,
  );
  app.get(
    `/tenant/:tenantId/security-guard/autocomplete`,
    require('./securityGuardAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/security-guard`,
    require('./securityGuardList').default,
  );
  app.get(
    `/tenant/:tenantId/security-guard/:id`,
    require('./securityGuardFind').default,
  );
};
