export default (app) => {
  app.get(
    `/security-guard/public`,
    require('./securityGuardPublicFind').default,
  );
  app.post(
    `/tenant/:tenantId/security-guard`,
    require('./securityGuardCreate').default,
  );
  app.put(
    `/tenant/:tenantId/security-guard/:id`,
    require('./securityGuardUpdate').default,
  );
  app.put(
    `/tenant/:tenantId/security-guard/self`,
    require('./securityGuardSelfUpdate').default,
  );
  app.post(
    `/tenant/:tenantId/security-guard/import`,
    require('./securityGuardImport').default,
  );
  app.get(
    `/tenant/:tenantId/security-guard/export`,
    require('./securityGuardExport').default,
  );
  app.get(
    `/tenant/:tenantId/security-guard/public`,
    require('./securityGuardPublicFind').default,
  );
  app.post(
    `/tenant/:tenantId/security-guard/invite`,
    require('./securityGuardInvite').default,
  );
  app.delete(
    `/tenant/:tenantId/security-guard`,
    require('./securityGuardDestroy').default,
  );
  app.post(
    `/tenant/:tenantId/security-guard/restore`,
    require('./securityGuardRestore').default,
  );
  app.post(
    `/tenant/:tenantId/security-guard/archive`,
    require('./securityGuardArchive').default,
  );
  app.get(
    `/tenant/:tenantId/security-guard/autocomplete`,
    require('./securityGuardAutocomplete').default,
  );
  app.get(
    `/tenant/:tenantId/security-guard`,
    require('./securityGuardList').default,
  );
  app.get(
    `/tenant/:tenantId/security-guard/:id`,
    require('./securityGuardFind').default,
  );

  // Security guard notes CRUD
  app.get(
    `/tenant/:tenantId/security-guard/:id/notes`,
    require('./securityGuardNotes').default,
  );
  app.post(
    `/tenant/:tenantId/security-guard/:id/notes`,
    require('./securityGuardNoteCreate').default,
  );
  app.put(
    `/tenant/:tenantId/security-guard/:id/notes/:noteId`,
    require('./securityGuardNoteUpdate').default,
  );
  app.delete(
    `/tenant/:tenantId/security-guard/:id/notes/:noteId`,
    require('./securityGuardNoteDestroy').default,
  );
};
